services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: gscore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456?A
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: